name: dart_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  dart_jsonwebtoken: ^3.2.0
  dotenv: ^4.2.0
  mongo_dart: ^0.10.5
  path: ^1.9.1
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  watcher: ^1.1.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
